//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_TYPES
    {
        public EXAM_TYPES()
        {
            this.EXAMS = new HashSet<EXAMS>();
        }
    
        public int EXAM_TYPE_ID { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual SUBJECTS SUBJECTS { get; set; }
        public virtual ICollection<EXAMS> EXAMS { get; set; }
    }
}
