//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOWED_CATS
    {
        public int ALLOWED_CAT_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> NEWS_SUB_CAT_ID { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual NEWS_SUB_CATS NEWS_SUB_CATS { get; set; }
    }
}
