//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINS
    {
        public int ADMIN_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string ADMIN_NAME { get; set; }
        public string ADMIN_POSITION { get; set; }
        public Nullable<int> NEWS_CAT_ID { get; set; }
        public Nullable<short> FULL_ADMIN { get; set; }
        public Nullable<short> ALLOW_ADD_NEWS { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual NEWS_CATS NEWS_CATS { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
