//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHMENTS
    {
        public int ATTACH_ID { get; set; }
        public Nullable<int> MESSAGE_ID { get; set; }
        public string ATTACH_FILENAME { get; set; }
        public byte[] ATTACHMENT { get; set; }
    
        public virtual MESSAGES MESSAGES { get; set; }
    }
}
