//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_QUESTIONS
    {
        public DOC_QUESTIONS()
        {
            this.DOC_ANSWERS = new HashSet<DOC_ANSWERS>();
            this.ANSWERS_USERS = new HashSet<ANSWERS_USERS>();
        }
    
        public int QUESTION_ID { get; set; }
        public string VALUE { get; set; }
        public int TYPE { get; set; }
        public int DOCUMENT_ID { get; set; }
    
        public virtual ICollection<DOC_ANSWERS> DOC_ANSWERS { get; set; }
        public virtual DOCUMENTS DOCUMENTS { get; set; }
        public virtual ICollection<ANSWERS_USERS> ANSWERS_USERS { get; set; }
    }
}
