//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS
    {
        public DOCUMENTS()
        {
            this.DOC_QUESTIONS = new HashSet<DOC_QUESTIONS>();
            this.DOCUMENT_USER = new HashSet<DOCUMENT_USER>();
        }
    
        public int DOCUMENT_ID { get; set; }
        public string NAME { get; set; }
        public int SCHOOL_ID { get; set; }
    
        public virtual ICollection<DOC_QUESTIONS> DOC_QUESTIONS { get; set; }
        public virtual ICollection<DOCUMENT_USER> DOCUMENT_USER { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
    }
}
