//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATION_YEARS
    {
        public EDUCATION_YEARS()
        {
            this.LESSONS = new HashSet<LESSONS>();
            this.RESOURCES = new HashSet<RESOURCES>();
            this.SESSIONS = new HashSet<SESSIONS>();
        }
    
        public int EDUCATION_YEAR_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual ICollection<LESSONS> LESSONS { get; set; }
        public virtual ICollection<RESOURCES> RESOURCES { get; set; }
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
    }
}
