//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMS
    {
        public int EXAM_ID { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public Nullable<int> EXAM_TYPE_ID { get; set; }
        public string EXAM_NAME { get; set; }
        public Nullable<decimal> EXAM_WEGHIT { get; set; }
        public Nullable<int> EXAM_MAX { get; set; }
        public Nullable<int> EXAM_PASS { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual EXAM_TYPES EXAM_TYPES { get; set; }
        public virtual SUBJECTS SUBJECTS { get; set; }
    }
}
