//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        public GROUPS()
        {
            this.GROUP_MEMBERS = new HashSet<GROUP_MEMBERS>();
            this.JOIN_GROUPS = new HashSet<JOIN_GROUPS>();
            this.NEWS_ACL_GROUPS = new HashSet<NEWS_ACL_GROUPS>();
        }
    
        public int GROUP_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual ICollection<GROUP_MEMBERS> GROUP_MEMBERS { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual ICollection<JOIN_GROUPS> JOIN_GROUPS { get; set; }
        public virtual ICollection<NEWS_ACL_GROUPS> NEWS_ACL_GROUPS { get; set; }
    }
}
