//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLYDAYS
    {
        public int HOLYDAY_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> HOLYDAY_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual SCHOOLS SCHOOLS { get; set; }
    }
}
