//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOIN_GROUPS
    {
        public int JOIN_GROUP_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
