//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSONS
    {
        public LESSONS()
        {
            this.LESSONS_SECTIONS = new HashSet<LESSONS_SECTIONS>();
        }
    
        public int LESSON_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EDUCATION_YEAR_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public Nullable<int> TEACHER_ID { get; set; }
        public string TITLE { get; set; }
        public string OBJECTIVE { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<short> ORDR { get; set; }
        public string NOTE { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
    
        public virtual CLASSES CLASSES { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual SUBJECTS SUBJECTS { get; set; }
        public virtual TEACHERS TEACHERS { get; set; }
        public virtual SESSIONS SESSIONS { get; set; }
        public virtual ICollection<LESSONS_SECTIONS> LESSONS_SECTIONS { get; set; }
        public virtual EDUCATION_YEARS EDUCATION_YEARS { get; set; }
    }
}
