//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSONS_SECTIONS
    {
        public int LESSON_SECTION_ID { get; set; }
        public Nullable<int> LESSON_ID { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
        public Nullable<short> ORDR { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<short> TEACHER { get; set; }
        public Nullable<short> STUDENTS { get; set; }
    
        public virtual RESOURCES RESOURCES { get; set; }
        public virtual LESSONS LESSONS { get; set; }
    }
}
