//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINS> ADMINS { get; set; }
        public DbSet<CLASSES> CLASSES { get; set; }
        public DbSet<GROUP_MEMBERS> GROUP_MEMBERS { get; set; }
        public DbSet<GROUPS> GROUPS { get; set; }
        public DbSet<JOIN_GROUPS> JOIN_GROUPS { get; set; }
        public DbSet<NEWS> NEWS { get; set; }
        public DbSet<NEWS_ACL_CLASSES> NEWS_ACL_CLASSES { get; set; }
        public DbSet<NEWS_ACL_GROUPS> NEWS_ACL_GROUPS { get; set; }
        public DbSet<NEWS_ACL_SUBJECTS> NEWS_ACL_SUBJECTS { get; set; }
        public DbSet<NEWS_CATS> NEWS_CATS { get; set; }
        public DbSet<NEWS_MEDIAS> NEWS_MEDIAS { get; set; }
        public DbSet<NEWS_SUB_CATS> NEWS_SUB_CATS { get; set; }
        public DbSet<PARENTS> PARENTS { get; set; }
        public DbSet<SCHOOLS> SCHOOLS { get; set; }
        public DbSet<STUDENT_SUBJECTS> STUDENT_SUBJECTS { get; set; }
        public DbSet<STUDENTS> STUDENTS { get; set; }
        public DbSet<STUDENTS_PARENTS> STUDENTS_PARENTS { get; set; }
        public DbSet<SUBJECTS> SUBJECTS { get; set; }
        public DbSet<TEACHER_SUBJECTS> TEACHER_SUBJECTS { get; set; }
        public DbSet<TEACHERS> TEACHERS { get; set; }
        public DbSet<USER_VOTES> USER_VOTES { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<VOTING_CHOICES> VOTING_CHOICES { get; set; }
    }
}
