//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_SUB_CATS
    {
        public NEWS_SUB_CATS()
        {
            this.NEWS = new HashSet<NEWS>();
            this.ALLOWED_CATS = new HashSet<ALLOWED_CATS>();
        }
    
        public int NEWS_SUB_CAT_ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> NEWS_CAT_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual ICollection<NEWS> NEWS { get; set; }
        public virtual NEWS_CATS NEWS_CATS { get; set; }
        public virtual ICollection<ALLOWED_CATS> ALLOWED_CATS { get; set; }
    }
}
