//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_ACL_SUBJECTS
    {
        public int NEW_ACL_SUBJECT_ID { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
    
        public virtual NEWS NEWS { get; set; }
        public virtual SUBJECTS SUBJECTS { get; set; }
    }
}
