//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_MEDIAS
    {
        public int NEWS_MEDIA_ID { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public string NAME { get; set; }
        public byte[] ATTACH { get; set; }
        public string BODY3 { get; set; }
        public Nullable<short> TYPE { get; set; }
        public string BODY { get; set; }
    
        public virtual NEWS NEWS { get; set; }
    }
}
