//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES
    {
        public RESOURCES()
        {
            this.LESSONS_SECTIONS = new HashSet<LESSONS_SECTIONS>();
            this.RESOURCES_LINKS = new HashSet<RESOURCES_LINKS>();
        }
    
        public int RESOURCE_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EDUCATION_YEAR_ID { get; set; }
        public Nullable<int> RESOURCE_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string OBJECTIVE { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public string ATTACHMENT_NAME { get; set; }
        public string ATTACHMENT_EXT { get; set; }
        public Nullable<short> ATTACHMENT_TYPE { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
    
        public virtual ICollection<LESSONS_SECTIONS> LESSONS_SECTIONS { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual ICollection<RESOURCES_LINKS> RESOURCES_LINKS { get; set; }
        public virtual EDUCATION_YEARS EDUCATION_YEARS { get; set; }
    }
}
