//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES_LINKS
    {
        public int RESOURCE_LINK_ID { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
        public Nullable<int> LINK_ID { get; set; }
        public Nullable<short> LINK_WITH { get; set; }
    
        public virtual RESOURCES RESOURCES { get; set; }
    }
}
