//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOLS
    {
        public SCHOOLS()
        {
            this.ADMINS = new HashSet<ADMINS>();
            this.CLASSES = new HashSet<CLASSES>();
            this.DOCUMENTS = new HashSet<DOCUMENTS>();
            this.GROUPS = new HashSet<GROUPS>();
            this.NEWS_CATS = new HashSet<NEWS_CATS>();
            this.PARENTS = new HashSet<PARENTS>();
            this.RESOURCES = new HashSet<RESOURCES>();
            this.SESSIONS = new HashSet<SESSIONS>();
            this.STUDENTS = new HashSet<STUDENTS>();
            this.SUBJECTS = new HashSet<SUBJECTS>();
            this.TEACHERS = new HashSet<TEACHERS>();
            this.USERS = new HashSet<USERS>();
            this.LESSONS = new HashSet<LESSONS>();
            this.HOLYDAYS = new HashSet<HOLYDAYS>();
            this.EDUCATION_YEARS = new HashSet<EDUCATION_YEARS>();
        }
    
        public int SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public byte[] LOGO { get; set; }
        public string SLOGEN { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<int> ALLOWED_USER_COUNT { get; set; }
        public Nullable<System.DateTime> EXPIER_DATE { get; set; }
        public Nullable<short> MESSAGING { get; set; }
        public Nullable<short> GRADES { get; set; }
        public Nullable<short> WOMEWORKS { get; set; }
        public Nullable<short> SCHEDULE { get; set; }
        public Nullable<short> PARENT_TO_TEACHER { get; set; }
        public Nullable<short> TEACHER_TO_PARENT { get; set; }
        public Nullable<short> TEACHER_TO_STUDENT { get; set; }
        public Nullable<short> STUDENT_TO_TEACHER { get; set; }
        public Nullable<short> FETCH_SIZE { get; set; }
        public Nullable<short> TYPE { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
        public Nullable<short> SESSION_DURATION { get; set; }
    
        public virtual ICollection<ADMINS> ADMINS { get; set; }
        public virtual ICollection<CLASSES> CLASSES { get; set; }
        public virtual ICollection<DOCUMENTS> DOCUMENTS { get; set; }
        public virtual ICollection<GROUPS> GROUPS { get; set; }
        public virtual ICollection<NEWS_CATS> NEWS_CATS { get; set; }
        public virtual ICollection<PARENTS> PARENTS { get; set; }
        public virtual ICollection<RESOURCES> RESOURCES { get; set; }
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
        public virtual ICollection<STUDENTS> STUDENTS { get; set; }
        public virtual ICollection<SUBJECTS> SUBJECTS { get; set; }
        public virtual ICollection<TEACHERS> TEACHERS { get; set; }
        public virtual ICollection<USERS> USERS { get; set; }
        public virtual ICollection<LESSONS> LESSONS { get; set; }
        public virtual ICollection<HOLYDAYS> HOLYDAYS { get; set; }
        public virtual ICollection<EDUCATION_YEARS> EDUCATION_YEARS { get; set; }
    }
}
