//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONS
    {
        public SESSIONS()
        {
            this.STUDENT_SESSION_DETAILS = new HashSet<STUDENT_SESSION_DETAILS>();
            this.LESSONS = new HashSet<LESSONS>();
            this.HEADLINES = new HashSet<HEADLINES>();
        }
    
        public int SESSION_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EDUCATION_YEAR_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public string TITLE { get; set; }
        public string OBJECTIVE { get; set; }
        public Nullable<short> ORDR { get; set; }
        public Nullable<System.DateTime> EXPECTED_DATE { get; set; }
    
        public virtual CLASSES CLASSES { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual SUBJECTS SUBJECTS { get; set; }
        public virtual ICollection<STUDENT_SESSION_DETAILS> STUDENT_SESSION_DETAILS { get; set; }
        public virtual ICollection<LESSONS> LESSONS { get; set; }
        public virtual ICollection<HEADLINES> HEADLINES { get; set; }
        public virtual EDUCATION_YEARS EDUCATION_YEARS { get; set; }
    }
}
