//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        public STUDENTS()
        {
            this.STUDENT_SESSION_DETAILS = new HashSet<STUDENT_SESSION_DETAILS>();
            this.STUDENT_SUBJECTS = new HashSet<STUDENT_SUBJECTS>();
            this.STUDENTS_EXAM = new HashSet<STUDENTS_EXAM>();
            this.STUDENTS_NOTES = new HashSet<STUDENTS_NOTES>();
            this.STUDENTS_PARENTS = new HashSet<STUDENTS_PARENTS>();
        }
    
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public byte[] STUDENT_PHOTO { get; set; }
        public string STUDENT_FATHER { get; set; }
        public string STUDENT_MATHER { get; set; }
        public Nullable<System.DateTime> STDENT_BIRTHDATE { get; set; }
        public string STUDENT_MPHONE { get; set; }
        public string STUDENT_LPHONE { get; set; }
        public string STUDENT_EMAIL { get; set; }
        public string STUDENT_FACEBOOK { get; set; }
        public string STUDENT_TWEETER { get; set; }
        public Nullable<short> STUDENT_ACTIVE { get; set; }
        public Nullable<short> ALLOW_ADD_NEWS { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual CLASSES CLASSES { get; set; }
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual ICollection<STUDENT_SESSION_DETAILS> STUDENT_SESSION_DETAILS { get; set; }
        public virtual ICollection<STUDENT_SUBJECTS> STUDENT_SUBJECTS { get; set; }
        public virtual ICollection<STUDENTS_EXAM> STUDENTS_EXAM { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual ICollection<STUDENTS_NOTES> STUDENTS_NOTES { get; set; }
        public virtual ICollection<STUDENTS_PARENTS> STUDENTS_PARENTS { get; set; }
    }
}
