//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS_EXAM
    {
        public int STUDENTS_EXAM_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EXAM_ID { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public string STUDENT_GRADE_NOTES { get; set; }
        public Nullable<short> ABSENT { get; set; }
        public Nullable<decimal> GRADE { get; set; }
    
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
