//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_HEADLINES
    {
        public int SUB_HEADLINE_ID { get; set; }
        public int HEADLINE_ID { get; set; }
        public string TITLE { get; set; }
        public string OBJECTIVE { get; set; }
        public string NOTE { get; set; }
    
        public virtual HEADLINES HEADLINES { get; set; }
    }
}
