//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS
    {
        public TEACHERS()
        {
            this.TEACHER_SUBJECTS = new HashSet<TEACHER_SUBJECTS>();
        }
    
        public int TEACHER_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string TEACHER_NAME { get; set; }
        public byte[] TEACHER_PHOTO { get; set; }
        public string TEACHER_FATHER { get; set; }
        public string TEACHER_MATHER { get; set; }
        public Nullable<System.DateTime> TEACHER_BIRTHDATE { get; set; }
        public string TEACHER_MPHONE { get; set; }
        public string TEACHER_LPHONE { get; set; }
        public string TEACHER_AREA { get; set; }
        public string TEACHER_ADDRES { get; set; }
        public string TEACHER_EMAIL { get; set; }
        public string TEACHER_FACEBOOK { get; set; }
        public string TEACHER_TWEETER { get; set; }
        public string TEACHER_NOTE { get; set; }
        public Nullable<short> TEACHER_ACTIVE { get; set; }
        public Nullable<short> ALLOW_ADD_NEWS { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual SCHOOLS SCHOOLS { get; set; }
        public virtual ICollection<TEACHER_SUBJECTS> TEACHER_SUBJECTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
