//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_VOTES
    {
        public int USER_VOTE_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> VOTING_CHOICE_ID { get; set; }
        public Nullable<System.DateTime> VOTING_DATE { get; set; }
        public string IMEI { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual VOTING_CHOICES VOTING_CHOICES { get; set; }
    }
}
