//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public NEWS()
        {
            this.NEWS_ACL_CLASSES = new HashSet<NEWS_ACL_CLASSES>();
            this.NEWS_ACL_GROUPS = new HashSet<NEWS_ACL_GROUPS>();
            this.NEWS_ACL_SUBJECTS = new HashSet<NEWS_ACL_SUBJECTS>();
            this.NEWS_MEDIAS = new HashSet<NEWS_MEDIAS>();
            this.USERS1 = new HashSet<USERS>();
            this.VOTING_CHOICES = new HashSet<VOTING_CHOICES>();
        }
    
        public int NEWS_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> NEWS_SUB_CAT_ID { get; set; }
        public string TITLE { get; set; }
        public string BODY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<short> TYPE { get; set; }
        public string HEADLINE { get; set; }
        public Nullable<int> ACCESSIBILITY { get; set; }
        public Nullable<short> VOTE_RESULT { get; set; }
        public Nullable<short> VOTE_COUNT { get; set; }
        public Nullable<short> VOTE_TYPE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<short> SHARABLE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<short> APPROVED { get; set; }
        public Nullable<short> HIERARCHY_TYPE { get; set; }
        public Nullable<System.DateTime> EVENT_DATE { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
    
        public virtual ICollection<NEWS_ACL_CLASSES> NEWS_ACL_CLASSES { get; set; }
        public virtual ICollection<NEWS_ACL_GROUPS> NEWS_ACL_GROUPS { get; set; }
        public virtual ICollection<NEWS_ACL_SUBJECTS> NEWS_ACL_SUBJECTS { get; set; }
        public virtual NEWS_SUB_CATS NEWS_SUB_CATS { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual ICollection<NEWS_MEDIAS> NEWS_MEDIAS { get; set; }
        public virtual ICollection<USERS> USERS1 { get; set; }
        public virtual ICollection<VOTING_CHOICES> VOTING_CHOICES { get; set; }
    }
}
