//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPI.Models.MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_ANSWERS
    {
        public DOC_ANSWERS()
        {
            this.ANSWERS_USERS = new HashSet<ANSWERS_USERS>();
        }
    
        public int ANSWER_ID { get; set; }
        public string VALUE { get; set; }
        public Nullable<int> QUESTION_ID { get; set; }
    
        public virtual DOC_QUESTIONS DOC_QUESTIONS { get; set; }
        public virtual ICollection<ANSWERS_USERS> ANSWERS_USERS { get; set; }
    }
}
